import { E2E_ACCOUNTS, E2E_CURSOS } from "@tcc/tests"
import type { APIRequestContext } from "@playwright/test"
import { expect, test } from "./fixtures/test"
import {
  expectReview,
  fillBasicInfo,
  fillMetadata,
  goToStep,
  gotoWizard,
  selectAluno,
  selectAvaliador,
  selectOrientador,
  submitWizard,
} from "./support/wizard"

/**
 * Fluxo principal do sistema: cadastro de uma defesa pelo wizard de 5 passos.
 *
 * Cada teste cria o próprio aluno (via API, com e-mail único) porque a regra
 * `aluno_curso_unique` permite uma única banca por aluno/curso — usar o aluno do seed
 * faria o segundo teste da suíte falhar com 409.
 */

async function findBancaByTitle(api: APIRequestContext, titulo: string) {
  const res = await api.get(`/banca?searchQuery=${encodeURIComponent(titulo)}&limit=100`)
  expect(res.ok(), `busca de banca falhou: ${res.status()}`).toBeTruthy()
  const body = (await res.json()) as {
    upcoming?: Array<{ id: number; tituloTrabalho: string; linkTrabalho: string | null }>
    past?: Array<{ id: number; tituloTrabalho: string; linkTrabalho: string | null }>
  }
  return [...(body.upcoming ?? []), ...(body.past ?? [])].find((banca) => banca.tituloTrabalho === titulo)
}

const RESUMO = "Resumo gerado pela suíte E2E para validar o cadastro de defesa."
const ABSTRACT = "Abstract generated by the E2E suite to validate defense registration."

test.describe("Cadastro de defesa", () => {
  test("cadastra uma defesa completa pelo wizard e persiste os dados", async ({
    asAdmin,
    factory,
    api,
    unique,
  }) => {
    const student = await factory.createStudent()
    const titulo = `Defesa E2E ${unique}`
    const linkTrabalho = `https://repositorio.ufba.br/handle/ri/${unique}`

    await gotoWizard(asAdmin)

    await fillBasicInfo(asAdmin, { titulo, resumo: RESUMO, abstract: ABSTRACT })
    await goToStep(asAdmin, 1)

    await selectAluno(asAdmin, student)
    await selectOrientador(asAdmin, E2E_ACCOUNTS.teacher.nome)
    /* A matrícula é derivada do aluno escolhido. */
    await expect(asAdmin.getByLabel("Matrícula")).toHaveValue(student.matricula)
    await goToStep(asAdmin, 2)

    await fillMetadata(asAdmin, {
      palavrasChave: "e2e, cadastro, defesa",
      turma: "GICC0002 PROJETO FINAL DE CURSO II",
      curso: E2E_CURSOS.bcc.nome,
      periodoAcademico: "2026.1",
      data: "2099-03-10",
      hora: "14:30",
      modalidade: "Remoto",
      local: "https://meet.google.com/e2e-cadastro",
      linkTrabalho,
    })
    await goToStep(asAdmin, 3)

    await selectAvaliador(asAdmin, 2, E2E_ACCOUNTS.teacher2.nome)
    await goToStep(asAdmin, 4)

    await expectReview(asAdmin, { titulo, aluno: student.nome, linkTrabalho })
    await submitWizard(asAdmin)

    /* Persistência: confere pela API, não só pela tela. */
    const created = await findBancaByTitle(api, titulo)
    expect(created, "a banca cadastrada não foi encontrada na API").toBeTruthy()
    expect(created?.linkTrabalho).toBe(linkTrabalho)

    /* Outra visão pública do mesmo dado: a página de detalhes. */
    await asAdmin.goto(`/banca/${created?.id}`)
    await expect(asAdmin.getByRole("heading", { name: titulo })).toBeVisible()
    await expect(asAdmin.getByRole("link", { name: "Baixar PDF do TCC" })).toHaveAttribute(
      "href",
      linkTrabalho,
    )
    await expect(asAdmin.getByText("GICC0002 PROJETO FINAL DE CURSO II")).toBeVisible()
  })

  test("cadastra defesa sem o link do PDF, que é opcional", async ({ asAdmin, factory, api, unique }) => {
    const student = await factory.createStudent()
    const titulo = `Defesa sem link E2E ${unique}`

    await gotoWizard(asAdmin)
    await fillBasicInfo(asAdmin, { titulo, resumo: RESUMO, abstract: ABSTRACT })
    await goToStep(asAdmin, 1)
    await selectAluno(asAdmin, student)
    await selectOrientador(asAdmin, E2E_ACCOUNTS.teacher.nome)
    await goToStep(asAdmin, 2)

    await fillMetadata(asAdmin, {
      palavrasChave: "e2e, opcional",
      turma: "GICC0002 PROJETO FINAL DE CURSO II",
      curso: E2E_CURSOS.bcc.nome,
      periodoAcademico: "2026.1",
      data: "2099-03-11",
      hora: "10:00",
      modalidade: "Presencial",
      local: "Sala 301 - Instituto de Computação",
    })
    await goToStep(asAdmin, 3)
    await selectAvaliador(asAdmin, 2, E2E_ACCOUNTS.teacher3.nome)
    await goToStep(asAdmin, 4)
    await submitWizard(asAdmin)

    const created = await findBancaByTitle(api, titulo)
    expect(created).toBeTruthy()
    expect(created?.linkTrabalho).toBeNull()

    /* Sem link, a seção "Trabalho Completo" não deve existir. */
    await asAdmin.goto(`/banca/${created?.id}`)
    await expect(asAdmin.getByRole("heading", { name: titulo })).toBeVisible()
    await expect(asAdmin.getByRole("heading", { name: "Trabalho Completo" })).toBeHidden()
    await expect(asAdmin.getByText("Sala 301 - Instituto de Computação")).toBeVisible()
  })

  test("bloqueia o avanço do wizard enquanto faltam campos obrigatórios", async ({ asAdmin }) => {
    await gotoWizard(asAdmin)

    /* Passo 1 sem nada preenchido: continua no passo 1. */
    await asAdmin.getByRole("button", { name: "Próximo" }).click()
    await expect(asAdmin.getByRole("heading", { name: "Informações Básicas" })).toBeVisible()
    await expect(asAdmin.getByText("Título é obrigatório")).toBeVisible()

    /* Preenche só o título: ainda falta resumo/abstract. */
    await asAdmin.getByLabel("Título do Trabalho").fill("Título sem resumo")
    await asAdmin.getByRole("button", { name: "Próximo" }).click()
    await expect(asAdmin.getByRole("heading", { name: "Informações Básicas" })).toBeVisible()
    await expect(asAdmin.getByText("Resumo é obrigatório")).toBeVisible()

    /* Com os três campos, avança. */
    await asAdmin.getByLabel("Resumo", { exact: true }).fill(RESUMO)
    await asAdmin.getByLabel("Abstract", { exact: true }).fill(ABSTRACT)
    await goToStep(asAdmin, 1)
  })

  test("permite voltar para o passo anterior sem perder o que foi digitado", async ({ asAdmin, unique }) => {
    const titulo = `Defesa navegação E2E ${unique}`

    await gotoWizard(asAdmin)
    await fillBasicInfo(asAdmin, { titulo, resumo: RESUMO, abstract: ABSTRACT })
    await goToStep(asAdmin, 1)

    await asAdmin.getByRole("button", { name: "Voltar" }).click()
    await expect(asAdmin.getByRole("heading", { name: "Informações Básicas" })).toBeVisible()
    await expect(asAdmin.getByLabel("Título do Trabalho")).toHaveValue(titulo)
    await expect(asAdmin.getByLabel("Resumo", { exact: true })).toHaveValue(RESUMO)
  })
})
