import {
  Bancas,
  cursos,
  db,
  InsertBanca,
  InsertCurso,
  InsertUser,
  InsertUsuarioBanca,
  Users,
  usuariosBancas,
} from "../src/database"

async function clearTables() {
  console.log("Clearing existing data...")
  // Delete in reverse order of creation due to FK constraints
  await db.delete(usuariosBancas)
  await db.delete(Bancas)
  await db.delete(Users)
  await db.delete(cursos)
  console.log("Tables cleared.")
}

async function seed() {
  await db.transaction(async (db) => {
    debugger
    // --- Seed Cursos ---
    console.log("Seeding cursos...")
    await db.insert(cursos).values({
      nome: "Ciência da Computação",
      sigla: "BCC",
    })
    console.log(`Seeded ${cursosData.length} cursos.`)

    // --- Seed Users ---
    console.log("Seeding users (usuarios)...")
    await db.insert(Users).values(usersData).onConflictDoNothing()
    console.log(`Seeded ${usersData.length} users.`)

    // --- Seed Bancas ---
    console.log("Seeding bancas...")

    await db.insert(Bancas).values(bancasData).onConflictDoNothing()
    console.log(`Seeded ${bancasData.length} bancas.`)

    // --- Seed UsuarioBanca ---
    console.log("Seeding usuarios_bancas...")
    await db.insert(usuariosBancas).values(usuariosBancasData).onConflictDoNothing()
    console.log(`Seeded ${usuariosBancasData.length} usuario_banca relations.`)
  })
}

seed().catch((error) => {
  console.error("Error seeding database:", error)
  process.exit(1)
})

const cursosData: InsertCurso[] = [
  {
    id: 1,
    nome: "Ciência da Computação", // Note: Encoding issues from SQL dump not fixed here
    sigla: "BCC",
  },
  {
    id: 2,
    nome: "Sistemas de Informação", // Note: Encoding issues from SQL dump not fixed here
    sigla: "BSI",
  },
]

const usersData: InsertUser[] = [
  {
    id: 9,
    username: "root",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "acae206f-e61c-11ee-9a7f-0242ac11",
    email: "root@root.com",
    nome: "Root User",
    school: "Root",
    academicTitle: "Bacharelado",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "3",
  },
  {
    id: 17,
    username: "freddurao",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "acb91f7a-e61c-11ee-9a7f-0242ac11",
    email: "fdurao@ufba.br",
    nome: "Frederico Araújo Durão",
    school: "Universidade Federal da Bahia",
    academicTitle: "Bacharelado",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-11-03 13:48:56"),
    updatedAt: new Date("2023-11-03 13:48:56"),
    role: "3",
  },
  {
    id: 57,
    username: "steffen.lewitzka",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "acbbac51-e61c-11ee-9a7f-0242ac11",
    email: "steffen.lewitzka@ufba.br",
    nome: "Steffen Lewitzka",
    school: "Universidade Federal da Bahia",
    academicTitle: "Pós Doutorado, PUC-Rio, 2005 Doutor em Ciência da Computação, CIn-UFPE, 2003",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "3",
  },
  {
    id: 58,
    username: "rodrigorgs",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "acbbb0b1-e61c-11ee-9a7f-0242ac11",
    email: "rodrigorgs@ufba.br",
    nome: "Rodrigo Rocha Gomes e Souza",
    school: "Universidade Federal da Bahia",
    academicTitle: "Doutor em Ciência da Computação, Engenharia de Software, UFBA, 2015",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "3",
  },
  {
    id: 59,
    username: "macedo",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "acbbb3f9-e61c-11ee-9a7f-0242ac11",
    email: "macedo@ufba.br",
    nome: "Raimundo José de Araújo Macêdo",
    school: "Universidade Federal da Bahia",
    academicTitle: "PhD, University of Newcastle upon Tyne, Inglaterra, 1994",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "3",
  },
  {
    id: 60,
    username: "gorender",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "acbbca65-e61c-11ee-9a7f-0242ac11",
    email: "gorender@ufba.br",
    nome: "Sérgio Gorender",
    school: "Universidade Federal da Bahia",
    academicTitle: "Doutor em Ciência da Computação. Centro de Informática - UFPE, 2005",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "3",
  },
  {
    id: 61,
    username: "ritasuzana",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "acbbd4f0-e61c-11ee-9a7f-0242ac11",
    email: "ritasuzana@dcc.ufba.br",
    nome: "Rita Suzana Pitangueira Maciel",
    school: "Universidade Federal da Bahia",
    academicTitle:
      "Pós-Doutorado - University of Waterloo. U.Waterloo, Canadá, 2015 Doutora em Ciência da Computação, UFPE, 2005",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "3",
  },
  {
    id: 62,
    username: "roberto.parente",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "acbbd91e-e61c-11ee-9a7f-0242ac11",
    email: "roberto.parente@ufba.br",
    nome: "Roberto Freitas Parente",
    school: "Universidade Federal da Bahia",
    academicTitle: "Doutor em Ciência da Computação, Combinatória - USP, 2016",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "3",
  },
  {
    id: 63,
    username: "ricardoar",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "acbbdc66-e61c-11ee-9a7f-0242ac11",
    email: "ricardoar@ufba.br",
    nome: "Ricardo Araújo Rios",
    school: "Universidade Federal da Bahia",
    academicTitle:
      "Pós-Doutorado em Ciências da Computação e Matemática Computacional, ICMC - USP, 2020 Doutor em Ciências da Computação e Matemática Computacional, ICMC - USP, 2013 Doutorado sanduíche, Université de Montréal (Montreal - CA) , 2012 Mestrado em Ciência da Computação, Universidade Federal de São Carlos. UFSCAR, 2008 Graduação em Ciência da Computação, Universidade Estadual do Sudoeste da Bahia, UESB, 2006",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "3",
  },
  {
    id: 64,
    username: "rubisley",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "acbbe31a-e61c-11ee-9a7f-0242ac11",
    email: "rubisley@ufba.br",
    nome: "Rubisley de Paula Lemes",
    school: "Universidade Federal da Bahia",
    academicTitle: "Doutor em Informática, UFPR, 2014",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "3",
  },
  {
    id: 65,
    username: "robespierre.pita",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "acbbe71a-e61c-11ee-9a7f-0242ac11",
    email: "robespierre.pita@ufba.br",
    nome: "Robespierre Dantas da Rocha Pita",
    school: "Universidade Federal da Bahia",
    academicTitle:
      "Doutor em Ciência da Computação - Universidade Federal da Bahia (UFBA), 2019 Mestre em Ciência da Computação - Universidade Federal da Bahia (UFBA), 2015 Especialista em Redes de Computadores - Universidade Salvador (UNIFACS), 2010 Graduado em Sistemas de Informação - Universidade Salvador (UNIFACS), 2009",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "3",
  },
  {
    id: 66,
    username: "melo",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "acbbea91-e61c-11ee-9a7f-0242ac11",
    email: "melo@dcc.ufba.br",
    nome: "Rafael Augusto de Melo",
    school: "Universidade Federal da Bahia",
    academicTitle:
      "Pós-Doutorado Universidade Federal Fluminense, UFF, 2014. Doutorado em Ciências da Engenharia (Matemática Aplicada) Université Catholique de Louvain, UCL, Bélgica, 2011. Mestrado em Computação  Universidade Federal Fluminense, UFF, 2007. Graduação em Ciência da Computação Universidade Federal de Lavras, UFLA, 2005.",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "3",
  },
  {
    id: 67,
    username: "manoel.mendonca",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "acbc0730-e61c-11ee-9a7f-0242ac11",
    email: "manoel.mendonca@ufba.br",
    nome: "Manoel Gomes de Mendonça Neto",
    school: "Universidade Federal da Bahia",
    academicTitle:
      "Pós-Doutorado Universidade de Maryland Em College Park, UMCP, Estados Unidos, 1998.  Doutorado em Ciência da Computação Universidade de Maryland Em College Park, UMCP, Estados Unidos, 1997.  Mestrado em Engenharia de Computação e Automação Industrial Universidade Estadual de Campinas, UNICAMP, 1990.  Graduação em Engenharia Elétrica, op. Eletrônica Universidade Federal da Bahia, UFBA, 1986.",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "3",
  },
  {
    id: 68,
    username: "maycon.leone",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "acbc196f-e61c-11ee-9a7f-0242ac11",
    email: "maycon.leone@ufba.br",
    nome: "Maycon Leone Maciel Peixoto",
    school: "Universidade Federal da Bahia",
    academicTitle:
      "Pós-Doutorado  Universidade Estadual de Campinas, UNICAMP, 2020. Doutorado em Ciências da Computação e Matemática Computacional Universidade de São Paulo, USP, 2012. Mestrado em Ciências da Computação e Matemática Computacional  Universidade de São Paulo, USP, 2008. Graduação em Bacharel em Ciência da Computação  Instituto Ensinar Brasil, FIC, 2005.",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "3",
  },
  {
    id: 69,
    username: "msouza1",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "acbc1e67-e61c-11ee-9a7f-0242ac11",
    email: "msouza1@ufba.br",
    nome: "Marlo Vieira dos Santos e Souza",
    school: "Universidade Federal da Bahia",
    academicTitle:
      "Doutorado em Computação  Universidade Federal do Rio Grande do Sul, UFRGS com período sanduíche em Utrecht University, 2016. Mestrado em Ciência da ComputaçãoPontifícia Universidade Católica do Rio Grande do Sul, PUCRS, 2012. Graduação em Matemática  Universidade Federal da Bahia, UFBA, 2009. Graduação em Ciência da ComputaçãoUniversidade Salvador, UNIFACS, 2008.",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "3",
  },
  {
    id: 70,
    username: "seixas.luma",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "acbea900-e61c-11ee-9a7f-0242ac11",
    email: "seixas.luma@ufba.br",
    nome: "Luma da Rocha Seixas",
    school: "Universidade Federal da Bahia",
    academicTitle: "Doutora em Ciência da Computação, UFPE, 2021",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "3",
  },
  {
    id: 71,
    username: "vaninha",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "acbeadfa-e61c-11ee-9a7f-0242ac11",
    email: "vaninha@ufba.br",
    nome: "Vaninha Vieira dos Santos",
    school: "Universidade Federal da Bahia",
    academicTitle:
      "Pós-Doutorado em Ciência da Computação, University of Southern California, USA, 2015 Doutora em Ciência da Computação, CIn/UFPE, 2008 Doutorado Sanduíche, Université Pierre et Marie Curie (LIP6), Paris-França, 2007 Mestre em Ciência da Computação, COPPE/UFRJ, 2003 Bacharel em Ciência da Computação, DCC/UFBA, 1999",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "3",
  },
  {
    id: 72,
    username: "pregnier",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "ad54f616-e61c-11ee-9a7f-0242ac11",
    email: "pregnier@ufba.br",
    nome: "Paul Denis Etienne Regnier",
    school: "Universidade Federal da Bahia",
    academicTitle: "Doutorado em Ciência da Computação, UFBA, 2012",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "3",
  },
  {
    id: 73,
    username: "lrebouca",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "ad725b19-e61c-11ee-9a7f-0242ac11",
    email: "lrebouca@ufba.br",
    nome: "Luciano Rebouças de Oliveira",
    school: "Universidade Federal da Bahia",
    academicTitle:
      "Post-Doctorate  Federal University of Bahia, UFBA, 2012.  PhD in Electrical and Computer Engineering  University of Coimbra, UC, Portugal, 2010.  Master in Mechatronics  Federal University of Bahia, UFBA, 2005.  Graduation in Computer Science  Federal University of Bahia, UFBA, 1997.",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "3",
  },
  {
    id: 74,
    username: "tatianenogueira",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "ad7263a5-e61c-11ee-9a7f-0242ac11",
    email: "tatianenogueira@ufba.br",
    nome: "Tatiane Nogueira Rios",
    school: "Universidade Federal da Bahia",
    academicTitle:
      "Pós-Doutora em Ciências da Computação e Matemática Computacional, ICMC - USP, 2020 Doutora em Ciências da Computação e Matemática Computacional, ICMC - USP, 2013 Doutorado sanduíche, McGill University (Montreal - Canadá), 2012  Mestrado em Ciência da Computação  Universidade Federal de São Carlos, UFSCAR, 2008.  Graduação em Ciência da Computação Universidade Estadual do Sudoeste da Bahia, UESB, 2006.",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "3",
  },
  {
    id: 75,
    username: "leobino",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "ad7266d7-e61c-11ee-9a7f-0242ac11",
    email: "leobino@ufba.br",
    nome: "Leobino Nascimento Sampaio",
    school: "Universidade Federal da Bahia",
    academicTitle:
      "Pós-Doutorado University of California Los Angeles, UCLA, 2020.  Doutorado em Ciências da Computação Universidade Federal de Pernambuco, UFPE, 2011.  Mestrado profissional em Redes de Computadores  Universidade Salvador, UNIFACS, 2004.  Graduação em Administração de Empresas Universidade Católica do Salvador, UCSAL, 1999.  Graduação em Ciência da Computação com ênfase em Análise de Sistemas  Universidade Salvador, UNIFACS, 1996.",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "3",
  },
  {
    id: 76,
    username: "gmlima",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "ad726ac2-e61c-11ee-9a7f-0242ac11",
    email: "gmlima@ufba.br",
    nome: "George Marconi de Araújo Lima",
    school: "Universidade Federal da Bahia",
    academicTitle:
      "Pós-Doutorado  Universidade Federal de Pernambuco, UFPE, 2016. Doutorado em Ciência da Computação  University of York, Inglaterra, 2003. Mestrado em Ciência da Computação  Universidade Estadual de Campinas, UNICAMP, 1996. Bacharelado em Ciência da Computação  Universidade Federal da Bahia, UFBA, 1993.",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "3",
  },
  {
    id: 78,
    username: "laisns",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "ad72701f-e61c-11ee-9a7f-0242ac11",
    email: "laisns@ufba.br",
    nome: "Laís do Nascimento Salvador",
    school: "Universidade Federal da Bahia",
    academicTitle:
      "Pós-DoutoradoUniversidade de São Paulo, USP, 2018. Doutorado em Engenharia Elétrica  Universidade de São Paulo, USP, 2001. Mestrado em Engenharia Elétrica Universidade de São Paulo, USP, 1995. Graduação em Bacharelado em Processamento de Dados Universidade Federal da Bahia, UFBA, 1990.",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "3",
  },
  {
    id: 79,
    username: "gustavobf",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "ad7273a7-e61c-11ee-9a7f-0242ac11",
    email: "gustavobf@ufba.br",
    nome: "Gustavo Bittencourt Figueiredo",
    school: "Universidade Federal da Bahia",
    academicTitle: "Doutor em Ciência da Computação, IC-UNICAMP, 2009",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "3",
  },
  {
    id: 80,
    username: "kaguero",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "ad72764c-e61c-11ee-9a7f-0242ac11",
    email: "kaguero@ufba.br",
    nome: "Karl Apaza Aguero",
    school: "Universidade Federal da Bahia",
    academicTitle: "Doutor em Ciência da Computação, UFPR, 2014",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "3",
  },
  {
    id: 81,
    username: "ivanmachado",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "ad728cbd-e61c-11ee-9a7f-0242ac11",
    email: "ivanmachado@dcc.ufba.br",
    nome: "Ivan do Carmo Machado",
    school: "Universidade Federal da Bahia",
    academicTitle:
      "Pós-Doutor em Engenharia de Software, UFBA, 2015 Doutor em Ciência da Computação, UFBA, 2014 Doutorado Sanduíche, Clemson University, EUA, 2012",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "3",
  },
  {
    id: 82,
    username: "fassis",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "ad728fbb-e61c-11ee-9a7f-0242ac11",
    email: "fassis@ufba.br",
    nome: "Flávio Morais de Assis Silva",
    school: "Universidade Federal da Bahia",
    academicTitle: "Doutor (Dr-Ing), Universidade Técnica de Berlim, Alemanha, 1999",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "3",
  },
  {
    id: 83,
    username: "esa",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "ad72924b-e61c-11ee-9a7f-0242ac11",
    email: "esa@dcc.ufba.br",
    nome: "Eduardo Santana de Almeida",
    school: "Universidade Federal da Bahia",
    academicTitle:
      "Pós-Doutorado University of California, Irvine, UCI, Estados Unidos, 2019. Pós-Doutorado Virginia Polytech Institute and State University, Virgina Tech, Estados Unidos, 2008. Doutorado em Ciências da Computação  Universidade Federal de Pernambuco, UFPE, 2007. Mestrado em Ciência da Computação  Universidade Federal de São Carlos, UFSCAR, 2003. Graduação em Ciência da Computação  Universidade Salvador, UNIFACS, 2000.",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "3",
  },
  {
    id: 84,
    username: "coimbra.danilo",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "ad7298ae-e61c-11ee-9a7f-0242ac11",
    email: "coimbra.danilo@ufba.br",
    nome: "Danilo Barbosa Coimbra",
    school: "Universidade Federal da Bahia",
    academicTitle:
      "Doutorado em Ciências da Computação e Matemática Computacional  Universidade de São Paulo, USP com período co-tutela em University of Groningen, 2016. Mestrado em Ciências da Computação  Universidade de São Paulo, USP, 2011. Graduação em Ciência da Computação  Instituto de Ensino Superior COC, 2008.",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "3",
  },
  {
    id: 85,
    username: "islame.felipe",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "ad729b7a-e61c-11ee-9a7f-0242ac11",
    email: "islame.felipe@ufba.br",
    nome: "Felipe Fernandes",
    school: "Universidade Federal da Bahia",
    academicTitle:
      "Doutorado em Ciência da Computação (PPgSC/UFRN, 2022) Mestrado em Sistemas e Computação (PPgSC/UFRN, 2018) Bacharelado em Ciência da Computação (UFRN, 2016)",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "3",
  },
  {
    id: 86,
    username: "abdalla",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "ad729e89-e61c-11ee-9a7f-0242ac11",
    email: "abdalla@ufba.br",
    nome: "Débora Abdalla Santos",
    school: "Universidade Federal da Bahia",
    academicTitle: "Doutora em Ciência da Computação, UFPE, 2000",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "3",
  },
  {
    id: 87,
    username: "dclaro",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "ad72a131-e61c-11ee-9a7f-0242ac11",
    email: "dclaro@ufba.br",
    nome: "Daniela Barreiro Claro",
    school: "Universidade Federal da Bahia",
    academicTitle: "Doutora em Ciência da Computação, Université d'Angers - França, 2006",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "3",
  },
  {
    id: 88,
    username: "fabiola",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "ad72a54a-e61c-11ee-9a7f-0242ac11",
    email: "fabiola@dcc.ufba.br",
    nome: "Fabíola Gonçalves Pereira Greve",
    school: "Universidade Federal da Bahia",
    academicTitle:
      "Post-Doctorate - Université Pierre et Marie Curie - Laboratoire d'Informatique de Paris, UPMC - LIP6, France, 2010. PhD in Informatics - Institut National de Recherche en Informatique et en Automatique - Siège, INRIA, France, 2002. Master in Computer Science - State University of Campinas, UNICAMP, 1991. Graduation in Data Processing - Federal University of Bahia, UFBA, 1988.",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "3",
  },
  {
    id: 89,
    username: "santanna",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "ad72b098-e61c-11ee-9a7f-0242ac11",
    email: "santanna@dcc.ufba.br",
    nome: "Cláudio Nogueira Sant'Anna",
    school: "Universidade Federal da Bahia",
    academicTitle:
      "Pós-Doutorado  Universidade Federal da Bahia, UFBA, 2009. Doutorado em Informática  Pontifícia Universidade Católica do Rio de Janeiro, PUC-Rio, 2008, em colaboração com a Universidade de Lancaster, Reino Unido. Mestrado em Informática  Pontifícia Universidade Católica do Rio de Janeiro, PUC-Rio, 2004. Bacharelado em Ciência da Computação Universidade Federal da Bahia, UFBA, 1997.",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "3",
  },
  {
    id: 90,
    username: "flach",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "ad72b43c-e61c-11ee-9a7f-0242ac11",
    email: "flach@ufba.br",
    nome: "Christina von Flach Garcia Chavez",
    school: "Universidade Federal da Bahia",
    academicTitle:
      "Pós-Doutorado  Université de Namur, UNAMUR, Bélgica, 2019. Pós-Doutorado  Pontifícia Universidade Católica do Rio de Janeiro, PUC-Rio, 2012. Doutorado em Informática  Pontifícia Universidade Católica do Rio de Janeiro, PUC-Rio, 2004. Mestrado em Ciência da Computação  Universidade Estadual de Campinas, UNICAMP, 1992. Bacharel em Ciência da Computação  Universidade Federal da Bahia, UFBA, 1987.",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "3",
  },
  {
    id: 91,
    username: "prazeres",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "ad72b6ef-e61c-11ee-9a7f-0242ac11",
    email: "prazeres@ufba.br",
    nome: "Cássio Vinicius Serafim Prazeres",
    school: "Universidade Federal da Bahia",
    academicTitle:
      "Pós Doutorado em Internet das Coisas, National University of Ireland, Galway, 2015 Doutorado em Ciência da Computação, USP/ICMC, 2009 Mestrado em Ciência da Computação - Universidade Salvador, UNIFACS, 2003 Bacharel em Ciência da Computação - Universidade Salvador, UNIFACS, 2000",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "1",
  },
  {
    id: 92,
    username: "antonio.apolinario",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "ad72b9a3-e61c-11ee-9a7f-0242ac11",
    email: "antonio.apolinario@ufba.br",
    nome: "Antonio Lopes Apolinario Junior",
    school: "Universidade Federal da Bahia",
    academicTitle:
      "Doutorado em Engenharia de Sistemas e Computação  Universidade Federal do Rio de Janeiro, UFRJ, 2004.Mestrado em Engenharia de Sistemas e Computação  Universidade Federal do Rio de Janeiro, UFRJ, 1995.Bacharelado em Matematica Mod Informatica  Universidade do Estado do Rio de Janeiro, UERJ, 1991.",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "3",
  },
  {
    id: 93,
    username: "bruno.ps",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "ad72bc44-e61c-11ee-9a7f-0242ac11",
    email: "bruno.ps@ufba.br",
    nome: "Bruno Pereira dos Santos",
    school: "Universidade Federal da Bahia",
    academicTitle:
      "Doutorado em Ciências da Computação  Universidade Federal de Minas Gerais, UFMG, 2019. Mestrado em Ciências da Computação  Universidade Federal de Minas Gerais, UFMG, 2015. Graduação em Ciência da Computação  Universidade Estadual de Santa Cruz, UESC, 2012.",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "3",
  },
  {
    id: 94,
    username: "frieda",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "ad7551a3-e61c-11ee-9a7f-0242ac11",
    email: "frieda@ufba.br",
    nome: "Anna Friedericka Schwarzelmuller",
    school: "Universidade Federal da Bahia",
    academicTitle:
      "Mestre em Ciência da Informação, UFBA, 2004  Especialista em Redes de Computadores,UFRJ, 1994  Especialista em linguagens de programação,UNICAMP, 1979",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "3",
  },
  {
    id: 95,
    username: "aliriosa",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "ad755647-e61c-11ee-9a7f-0242ac11",
    email: "aliriosa@ufba.br",
    nome: "Alírio Santos de Sá",
    school: "Universidade Federal da Bahia",
    academicTitle: "Doutor em Ciência da Computação, DMCC-UFBA, 2011",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2023-08-09 11:16:17"),
    updatedAt: new Date("2023-08-09 11:16:17"),
    role: "3",
  },
  {
    id: 102,
    username: "IsaqueCopque",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "ad755b9b-e61c-11ee-9a7f-0242ac11",
    email: "isaque.copque@ufba.br",
    nome: "Isaque Santana Copque",
    school: "UFBA",
    academicTitle: "Bacharelado",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2024-02-27 13:40:54"),
    updatedAt: new Date("2024-02-27 13:40:54"),
    role: "0",
  },
  {
    id: 103,
    username: "joao.p",
    passwordHash: "$2y$13$9fWEoo.5.I9fSI8vQyKzJe1hCWu0qukZMVersQgJJRxt63Z11kXGe",
    authKey: "ad755e3c-e61c-11ee-9a7f-0242ac11",
    email: "contato.joaocomp@gmail.com",
    nome: "João Pedro Brito Silva",
    school: "Universidade Federal da Bahia",
    academicTitle: "Bacharelado",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2024-03-09 20:52:48"),
    updatedAt: new Date("2024-03-09 20:52:48"),
    role: "0",
  },
  {
    id: 105,
    username: "alberto",
    passwordHash: "$2y$13$Dj0EjuymiSPLsKw8ViW5quwU.xrufWLAA6k66b9ULRtprTOuai9TS",
    authKey: "dL2DA0OAZYqmfJxYlT2JvvXlq4BFKO5t",
    email: "alberto.oliveira@ufba.br",
    nome: "Alberto Oliveira Santos",
    school: "Universidade Federal da Bahia",
    academicTitle: "Bacharel",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2024-05-02 11:52:37"),
    updatedAt: new Date("2024-05-02 11:52:37"),
    role: "0",
  },
  {
    id: 106,
    username: "teste",
    passwordHash: "$2y$13$rUH.LZl1xJBr/fwpzw8g2.YOP1eOl3qozfPlg01OkloJmDEOdkmI6",
    authKey: "4NgUeGMylHCwjiW4h8GMYT6iW3J8LS49",
    email: "teste@teste.com.br",
    nome: "Orientador Teste",
    school: "UFBA",
    academicTitle: "Doutor",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2024-05-08 14:55:21"),
    updatedAt: new Date("2024-05-08 14:55:21"),
    role: "3",
  },
  {
    id: 107,
    username: "murilo.guerreiro",
    passwordHash: "$2y$13$wT/lWjkyz31VlxSPLAH/f.HK6eU04r5f3GYxLGuag6Afw1M.IxrVW",
    authKey: "7iJnxCO4L2x4JFyBFf5ScZmaVfjQxqfd",
    email: "murilo.guerreiro@ufba.br",
    nome: "Murilo Guerreiro Arouca",
    school: "UFBA",
    academicTitle: "Mestre",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2024-05-22 12:49:31"),
    updatedAt: new Date("2024-05-22 12:49:31"),
    role: "2",
  },
  {
    id: 108,
    username: "bruno_guardiani",
    passwordHash: "$2y$13$Ajua3qcC2e/f6.tkRTc/qu0Aj/ZR7I6l70m8XarH40hZlj3nHhD1i",
    authKey: "xTIXAAqik7oRzfE72vKQSqMxs5-hIXB0",
    email: "bruno.paolo@ufba.br",
    nome: "Bruno Guardiani",
    school: "Universidade Federal da Bahia (UFBA)",
    academicTitle: "Bacharel",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2024-05-22 13:02:24"),
    updatedAt: new Date("2024-05-22 13:02:24"),
    role: "0",
  },
  {
    id: 109,
    username: "gabriela.bohana",
    passwordHash: "$2y$13$J.xbA/QOqQB7/dX2NvGr9.2/9kyZqzyjcR5nX76z6wc8e3DXOtTN6",
    authKey: "ROh65w3zMcgDianUVGIFhb-LY_L4utC1",
    email: "gabibohana@gmail.com",
    nome: "Gabriela Bohana Ferreira Lima",
    school: "UFBA",
    academicTitle: "Bacharel",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2024-06-20 02:06:18"),
    updatedAt: new Date("2024-06-20 02:06:18"),
    role: "0",
  },
  {
    id: 110,
    username: "eduardoferreiradasilva",
    passwordHash: "$2y$13$hm6YDaq3Hl6hzgKfLTsff.hLfRh3unrBG5x46/cbGhIXBxIQcWmba",
    authKey: "9_fCtnyjBRyB2S92EvZI2sDl70rUr4o1",
    email: "eduardoferreira@ufba.br",
    nome: "Eduardo Ferreira da Silva",
    school: "UFBA",
    academicTitle: "Mestre",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2024-06-20 16:32:45"),
    updatedAt: new Date("2024-06-20 16:32:45"),
    role: "2",
  },
  {
    id: 111,
    username: "contato.joaocomp2",
    passwordHash: "$2y$13$/RaSl3r/nGOwZTtyAoaeuOV7fjAY2vaouY7JRXLeyTwA0n228cx5C",
    authKey: "jO5vwr-D5sKuYFTa_8DGkNW7jfWNKmLc",
    email: "contato.joaocomp2@gmail.com",
    nome: "João Pedro Brito Silva 2",
    school: "UFBA",
    academicTitle: "Doutor",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2024-07-07 18:23:27"),
    updatedAt: new Date("2024-07-07 18:23:27"),
    role: "2",
  },
  {
    id: 112,
    username: "username",
    passwordHash: "$2y$13$z0br7bhgwl0y8rDFqpB67OgnZYx/yayp1tPvlR8q3n3YuOVWV0Fza",
    authKey: "_hRz-OfR8i4Fn0f_XhBERbdK0amvAplm",
    email: "teste2@teste.com.br",
    nome: "João Pedro Brito Silva Registrado",
    school: "UFBA",
    academicTitle: "Titulo",
    lattesUrl: null,
    status: "user",
    createdAt: new Date("2024-08-19 20:03:48"),
    updatedAt: new Date("2024-08-19 20:03:48"),
    role: "0",
  },
]

const bancasData: InsertBanca[] = [
  {
    id: 1,
    cursoId: 1,
    autor: "Isaque Santana Copque",
    turma: "2019.1",
    ano: "2024",
    semestreLetivo: "1",
    matricula: "219120256",
    modalidade: "local", // from tipo_banca
    tituloTrabalho: "EventIC: An Academic Event Recommender System for the Institute of Computing",
    resumo:
      "Event promotion platforms play a crucial role in fostering connections because they can extend the reach and visibility of events. In the academic environment, characterized by frequent lectures, seminars, and conferences organized by various research groups, these tools enable students, researchers, and interested individuals to access information easily, driving the dissemination of knowledge within the scientific community.  To further optimize this potential, a Recommendation System can be employed to help users discover relevant events. This work addressed integrating a recommendation mechanism, into a web application for promoting academic events, EventIC. Collaborative Filtering and Content-Based Filtering techniques were employed, and a comparison experiment of the results from these approaches was conducted. The metrics adopted in this study indicated that Collaborative Filtering produced more accurate recommendations.",
    abstract:
      "Event promotion platforms play a crucial role in fostering connections because they can extend the reach and visibility of events. In the academic environment, characterized by frequent lectures, seminars, and conferences organized by various research groups, these tools enable students, researchers, and interested individuals to access information easily, driving the dissemination of knowledge within the scientific community.  To further optimize this potential, a Recommendation System can be employed to help users discover relevant events. This work addressed integrating a recommendation mechanism, into a web application for promoting academic events, EventIC. Collaborative Filtering and Content-Based Filtering techniques were employed, and a comparison experiment of the results from these approaches was conducted. The metrics adopted in this study indicated that Collaborative Filtering produced more accurate recommendations.",
    palavrasChave: "Recommender System, Collaborative FIltering, Content-Based Filtering",
    dataRealizacao: new Date("2024-03-11 08:30:22"),
    notaFinal: null,
    local: "Salvador",
    visible: true, // from visible = 1
  },
  {
    id: 2,
    cursoId: 1,
    autor: "Alberto Oliveira Santos",
    turma: "101000 T10",
    ano: "2024",
    semestreLetivo: "1",
    matricula: "218217201",
    modalidade: "remoto", // from tipo_banca
    tituloTrabalho: "Desenvolvimento e Avaliação de um Sistema Web de Apoio à Gestão de Projetos", // Encoding issues present
    resumo:
      "Projetos permeiam a sociedade, prazos, tarefas, mudanças de escopo, custos, entre outros fatores, influenciam no andamento de um projeto. Nesse sentido, devido a importância dos projetos no âmbito profissional faz-se necessário aplicar a gestão de projetos no cotidiano das empresas. De forma informatizada os Sistemas Web de Apoio à Gestão de Projetos (SWAGP) se popularizaram entre as empresas e instituições oferecendo ferramentas que apoiam na tomada de decisão e demonstram em tempo real a situação do projeto. Como forma de obter lucro, plataformas que oferecem esse tipo de solução passaram a incluir limitações ao seu plano grátis, impossibilitando o uso por pequenas empresas e no uso educacional de desenvolvimento de projetos. Neste trabalho será proposto um sistema web gratuito capaz de facilitar o gerenciamento de múltiplos projetos, oferecendo ferramentas que são comumente encontradas em softwares pagos.", // Encoding issues present
    abstract:
      "Projects permeate society, deadlines, tasks, scope changes, costs, among other factors, influence the progress of a project. In this sense, due to the importance of projects in the professional sphere, it is necessary to apply project management in the daily lives of companies. In a computerized way, Web Project Management Support Systems (WPMSS) have become popular among companies and institutions, offering tools that support decision-making and demonstrate the project status in real time. As a way of making a profit, platforms that offer this type of solution have started to include limitations to their free plan, making it impossible to use by small businesses and in educational use for project development. In this work, a free web system will be proposed capable of facilitating the management of multiple projects, offering tools that are commonly found in paid software.",
    palavrasChave: "Gestão, Projetos, Software", // Encoding issues present
    dataRealizacao: new Date("2024-06-10 11:00:25"),
    notaFinal: null,
    local: "https://meet.google.com/mxk-uuof-tza",
    visible: false, // from visible = 0
  },
  {
    id: 6,
    cursoId: 1,
    autor: "Bruno Guardiani",
    turma: "101000",
    ano: "2024",
    semestreLetivo: "1",
    matricula: "217216759",
    modalidade: "remoto", // from tipo_banca
    tituloTrabalho: "Um Sistema de Recomendação baseado em Conteúdo para Recomendação de Vagas de Emprego", // Encoding issues present
    resumo: "Sistema de Recomendação para Empregos",
    abstract:
      "At present, every web system generates a large amount of data based on the information that users make available. For instance, social media platforms like LinkedIn, which help users find the best match for their skills and the available vacancies on the platform. However, extracting useful data from these platforms is not straightforward. Hence, recommendation algorithms (RAs) are implemented on these websites. A well-known RA is content-based filtering, which takes into account the vacancyÔÇÖs descriptive data (e.g. skills, soft skills) to recommend jobs that align with the userÔÇÖs descriptive characteristics. In addition, thereÔÇÖs some ways to make this approach get more effective integrating similarity calculation methodologies such as: Cosine Similarity, Jaccard, and Pearson.", // Encoding issues present
    palavrasChave: "recommendation system, content-based, vacancy, jobs",
    dataRealizacao: new Date("2024-06-10 09:30:07"),
    notaFinal: null,
    local: "https://meet.google.com/mgx-mtri-gne?hs=224",
    visible: false, // from visible = 0
  },
  {
    id: 7,
    cursoId: 1,
    autor: "Gabriela Bohana Ferreira Lima",
    turma: "MATA67",
    ano: "2024",
    semestreLetivo: "1",
    matricula: "216220011",
    modalidade: "remoto", // from tipo_banca
    tituloTrabalho: "Um Sistema de Recomendação de filmes baseado em regras semânticas", // Encoding issues present
    resumo:
      "Com o advento da Web, usuários passaram a ter mais liberdade na criação e compartilhamento de conteúdo, gerando um grande volume de dados e tornando cada vez mais difícil tomar decisões sobre o que é relevante ou não, o que por sua vez gera um problema conhecido como sobrecarga de informação. Diante disso, percebe-se que é necessário a adoção de mecanismos inteligentes para a realização dessa tarefa de filtragem de conteúdo personalizado. Logo, este trabalho propõe um Sistema de Recomendação baseado em conteúdo que utiliza Web Semântica para gerar recomendações de filmes utilizando regras semânticas. Para isso, foi criada uma ontologia e as regras foram utilizadas para gerar as inferências. Um experimento offline foi realizado e resultados mostram que o sistema foi capaz de gerar recomendações relevantes em pelo menos 36\\% dos casos analisados.", // Encoding issues present
    abstract:
      "With the advent of the Web, users acquired more freedom to create and share content, producing a large volume of data and thus making it harder to decide whether something is relevant, leading to the problem known as information overload. In this context, it becomes necessary to adopt intelligent mechanisms to filter personalized content. Therefore, this work proposes a content-based Recommendation System that uses Semantic Web to generate movie recommendations using semantic rules. For this purpose, an ontology was created, and the rules were used to generate inferences. An offline experiment was carried out, and results show that the system could generate relevant recommendations in at least 36% of the cases analyzed.",
    palavrasChave:
      "sistema de recomendação, semântica, web semântica, recomendação, regra semântica, swrl, owl, protege,", // Encoding issues present
    dataRealizacao: new Date("2024-06-21 09:00:16"),
    notaFinal: null,
    local: "meet.google.com/nhq-jmmg-czu",
    visible: false, // from visible = 0
  },
  {
    id: 8,
    cursoId: 1,
    autor: "João Pedro Brito Silvadadasd",
    turma: "1",
    ano: "2024",
    semestreLetivo: "2",
    matricula: "214002414",
    modalidade: "remoto", // from tipo_banca
    tituloTrabalho: "Defesa para teste das agendas - Google Calendar",
    resumo: "Defesa para teste das agendas - Google Calendar",
    abstract: "Defesa para teste das agendas - Google Calendar",
    palavrasChave: "Keywords",
    dataRealizacao: new Date("2024-07-18 20:35:46"),
    notaFinal: null,
    local: "http://www.google.com.br/teste",
    visible: false, // from visible = 0
  },
]
const usuariosBancasData: InsertUsuarioBanca[] = [
  { id: 1, usuarioId: 17, bancaId: 1, role: "orientador", nota: "10" }, // Original nota was double 10
  { id: 2, usuarioId: 84, bancaId: 1, role: "avaliador", nota: null },
  { id: 3, usuarioId: 17, bancaId: 2, role: "orientador", nota: null },
  { id: 11, usuarioId: 81, bancaId: 2, role: "avaliador", nota: null },
  { id: 12, usuarioId: 67, bancaId: 2, role: "avaliador", nota: null },
  { id: 13, usuarioId: 107, bancaId: 1, role: "avaliador", nota: "10" }, // Original nota was double 10
  { id: 14, usuarioId: 17, bancaId: 6, role: "orientador", nota: null },
  { id: 15, usuarioId: 84, bancaId: 6, role: "avaliador", nota: "4" }, // Original nota was double 4
  { id: 16, usuarioId: 17, bancaId: 7, role: "orientador", nota: "9" }, // Original nota was double 9
  { id: 18, usuarioId: 110, bancaId: 7, role: "avaliador", nota: "9" }, // Original nota was double 9
  { id: 19, usuarioId: 84, bancaId: 7, role: "avaliador", nota: "9" }, // Original nota was double 9
  { id: 20, usuarioId: 17, bancaId: 8, role: "orientador", nota: null },
]
